Repository OpenVoiceOS/ovos-backend-client, pull requests merged in 2022-10, with the labels that each got.

#10 Feat/multiple backends + rename
  .github/workflows/build_tests.yml
  .github/workflows/notify_matrix.yml
  .github/workflows/publish_alpha.yml
  .github/workflows/unit_tests.yml
  README.md
  ovos_backend_client/__init__.py
  ovos_backend_client/api.py
  ovos_backend_client/backends/__init__.py
  ovos_backend_client/backends/base.py
  ovos_backend_client/backends/offline.py
  ovos_backend_client/backends/personal.py
  ovos_backend_client/backends/selene.py
  ovos_backend_client/cloud.py
  ovos_backend_client/config.py
  ovos_backend_client/database.py
  ovos_backend_client/exceptions.py
  ovos_backend_client/identity.py
  ovos_backend_client/pairing.py
  ovos_backend_client/settings.py
  ovos_backend_client/version.py
  requirements.txt
  requirements/offline.txt
  requirements/requirements.txt
  scripts/bump_alpha.py
  scripts/bump_build.py
  scripts/bump_major.py
  scripts/bump_minor.py
  scripts/remove_alpha.py
  selene_api/__init__.py
  selene_api/api.py
  setup.py
  test/license_tests.py
  test/test.wav
  test/unittests/test_selene_api.py
Labels: enhancement

#13 fix/pairing_check
  ovos_backend_client/backends/base.py
  ovos_backend_client/backends/offline.py
  ovos_backend_client/pairing.py
  test/unittests/test_selene_api.py
Labels: bug

#14 make offline DeviceApi slightly more useful
  ovos_backend_client/backends/offline.py
Labels: enhancement

#15 fix/ensure_valid_urls
  ovos_backend_client/api.py
  ovos_backend_client/backends/base.py
  ovos_backend_client/pairing.py
Labels: bug

#16 fix/pairing_code_callback
  ovos_backend_client/pairing.py
Labels: bug

#17 feat/ovos_backend
  README.md
  ovos_backend_client/api.py
  ovos_backend_client/backends/__init__.py
  ovos_backend_client/backends/base.py
  ovos_backend_client/backends/ovos.py
Labels: enhancement

#18 Fix typo in OfflineBackend
  ovos_backend_client/backends/offline.py
Labels: bug

#19 fix/remote_config
  ovos_backend_client/config.py
Labels: bug

#20 pairing_logs
  ovos_backend_client/backends/personal.py
  ovos_backend_client/pairing.py
Labels: enhancement

#22 fix/pairing_retry
  ovos_backend_client/backends/personal.py
Labels: bug

#21 deprecate/mk1_hardcoded_pairing_flow
  ovos_backend_client/pairing.py
Labels: refactor

#23 fix/settings_upload
  ovos_backend_client/backends/personal.py
Labels: bug
