Repository OpenVoiceOS/ovos-backend-client, pull requests merged in 2024-09, with the labels that each got.

#61 Remove oauth refresh endpoint
  ovos_backend_client/database.py
  ovos_backend_client/version.py
  test/unittests/test_database.py
Labels: bug, refactor, breaking

#75 chore:semver_versioning
  requirements/offline.txt
  requirements/requirements.txt
Labels: ignore-for-release

#78 refactor!:deprecate_refresh_endpoint
  ovos_backend_client/api.py
  ovos_backend_client/backends/base.py
  ovos_backend_client/backends/offline.py
  ovos_backend_client/backends/personal.py
Labels: breaking
